# Official nacos-k8s v1.0.2 chart values.
global:
  mode: cluster

nacos:
  image:
    repository: nacos/nacos-server
    tag: "v3.0.1"
    pullPolicy: IfNotPresent
  plugin:
    enable: true
    image:
      repository: nacos/nacos-peer-finder-plugin
      tag: "1.1"
      pullPolicy: IfNotPresent
  replicaCount: 3
  podManagementPolicy: Parallel
  domainName: cluster.local
  preferHostMode: hostname
  serverPort: 8848
  consolePort: 8080
  mcpPort: 9080
  authToken: nil
  identityKey: nil
  identityValue: nil
  storage:
    type: mysql
    db:
      host: "mysql-mysql-primary"
      name: "nacos"
      port: 3306
      username: "root"
      password: "mysqlroot123"
      param: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false"

persistence:
  enabled: true
  data:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi

service:
  type: ClusterIP
  port: 8848

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1
