# Official TDengine-Operator 3.0 chart values.
name: "tdengine"

image:
  repository: ""
  server: "tdengine/tdengine:3.3.6.9"

timezone: "Asia/Shanghai"

service:
  type: ClusterIP
services:
  server:
    type: ClusterIP
    replica: 3
    ports:
      tcp: [6041, 6030, 6060]
      udp: []
    volumes:
      - name: tier0
        mountPath: /data/taos0/
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
      - name: tier1
        mountPath: /data/taos1/
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
      - name: tier2
        mountPath: /data/taos2/
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    environment:
      TAOS_DEBUG_FLAG: "131"
    files:
      - name: cfg
        mountPath: /etc/taos/taos.cfg
        content: |
          dataDir /data/taos0/  0 1
          dataDir /data/taos1/  1 0
          dataDir /data/taos2/  2 0
